config/routes.rb
Rails.application.routes.draw do

  root 'application#landing'

  resources :users
  resources :picks, except: :new
  match 'emails/create' => 'emails#create', :via => :post
  get  'login',  to: 'sessions#login'
  post 'login',  to: 'sessions#begin'
  get  'logout', to: 'sessions#end'

  get  'signup', to: 'users#new', as: 'signup'
  post 'signup', to: 'users#create'

  get  'landing',  to: 'application#landing'

end

app/models/user.rb
class User < ActiveRecord::Base
	validates :username, uniqueness: true, allow_blank: true
	validates_format_of :username, :with => /\A[A-Za-z\d_]+\z/,
		message: "can only contain alpha-numeric characters and underscores with no spaces.",
		allow_blank: true

  validates :email, presence: true, uniqueness: true
  validates_format_of :email, with: /@/,
  	message: "is not in a valid format"
  
  validates :phone, uniqueness: true, allow_blank: true
  validates_format_of :phone, with: /\A(?:(?:\+?1\s*(?:[.-]\s*)?)?(?:\(\s*([2-9]1[02-9]|[2-9][02-8]1|[2-9][02-8][02-9])\s*\)|([2-9]1[02-9]|[2-9][02-8]1|[2-9][02-8][02-9]))\s*(?:[.-]\s*)?)?([2-9]1[02-9]|[2-9][02-9]1|[2-9][02-9]{2})\s*(?:[.-]\s*)?([0-9]{4})(?:\s*(?:#|x\.?|ext\.?|extension)\s*(\d+))?\z/,
  	message: "is not a valid phone number",
  	allow_blank: true

  validates :password, length: { within: 6..20 },
  	allow_blank: true	
  
  has_many :picks
  has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, except: [:create, :new]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save && @user.authenticate(user_params[:password])
      @user.active = true; @user.save
      Notifier.welcome_email(@user).deliver
      respond_to do |format|
        format.json { render json: ActiveSupport::JSON.encode(@user), status:200, location: @user}
        format.html {
          redirect_to user_path(@user)
          session[:user_id] = @user.id
        }
      end
    else
      respond_to do |format|
        format.json { render json: 'signup failed', status:400 }
          format.html {
            render :new
            flash[:failure] = "Signup failed."
          }
      end
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Profile updated."
       respond_to do |format|
        format.json { render json: 'this', status:200 }
          format.html {
            redirect_to user_path(@user)
          }
        end
    else
      respond_to do |format|
        format.json { render nothing: true, status:400 }
          format.html {
            render :edit
            flash[:failure] = "Update unsuccessful."
          }
      end
    end
  end

  def show
  end

  def destroy
    session[:user_id] = nil
    @user.active = false; @user.save
    redirect_to root_path
  end

  private

    def user_params
         params.require(:user).permit(:username, :email, :phone, :password)
    end

end

app/views/users/edit.html.erb
<%= form_for @user do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>Please fix <%= pluralize(@user.errors.count, "error") %>:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-content">
  <div class="row">
    <div class="centered">
      <% email = nil if local_assigns[:email].nil? %>
      <% if @user.active %>
        <div class="field">
          <p class = 'desc-field'>Username</p>
          <%= f.text_field :username, placeholder: "Name" , class:"imput-field"%>
        </div>
      <% end %>
      <div class="field">
        <p class = 'desc-field'>Email</p>
        <% if email %>
          <%= f.text_field :email, value: email %>
        <% else %>
          <%= f.text_field :email, placeholder: "Email",class:"imput-field" %>
        <% end %>
      </div>
      <% if @user.active %>
        <div class="field">
          <p class = 'desc-field'>Phone</p>
          <%= f.text_field :phone, placeholder: "Phone",class:"imput-field" %>
        </div>
      <% end %>
      <div class="field">
        <p class = 'desc-field'>Password</p>
        <%= f.password_field :password, placeholder: "Password",class:"imput-field" %>
      </div>
      <div class="actions">
        <% if @user.active %>
         <%= submit_tag 'Save', class: "edit-button" %>
        <% else %>
          <%= submit_tag 'create account', class: "edit-button" %>
        <% end -%>
      </div>
   </div>
  </div>
</div>

<% end %>

app/views/users/new.html.erb
<%= form_for @user do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>Please fix <%= pluralize(@user.errors.count, "error") %>:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-content">
<center>
  <div class="row">
    <p class = 'desc-create'> Create an Account</p>
    <div class="field">
      <%= f.text_field :email, placeholder: "Email", class:"imput-field"   %>
    </div>
    <div class="field">
      <%= f.password_field :password, placeholder: "Password", class:"imput-field"   %>
    </div>
    <div class="actions">
      <%= submit_tag 'signup', class: "button medium default radius nav-button" %>
    </div>
  </div>
</center>
</div>

<% end %>

app/views/users/show.html.erb
<center><%= link_to 'CREATE A PICK', pick_path, class: "button medium default radius nav-button" %></center>

<center><h1> PICK HISTORY </h1> </center>
 <center> <p class="history-description"> here are your lottery picks</p> </center>
 <center>
  <div class="user-picks">
    <% @session_id = session[:user_id] %>
    <div class="pick-history-list">
      <% @user.picks.each do |pick| %>
      <div class="pick-items">
          <div class="number-row">
            <%if pick.result %>
              <p class='pick-num'><%= pick.number %> -- <%= pick.result %></p>
            <%else%>
              <p class='pick-num'><%= pick.number %> -- <span class='pending'>Pending resoult</span></p>
            <%end%>
          </div>
          <div class="pick-info">
            <p class='pick-date'><%= pick.draw_date.to_s[0..10] %> • <%= pick.game.upcase %></p>
          </div>
          <div class="trash-pic">
             <%= link_to image_tag("trash.png", class:"trash"), pick, method: :delete %>
          </div>
      </div>
     <br>
    <% end %>
  </div>
</div>

</center>