config/routes.rb
Rails.application.routes.draw do

  root 'application#landing'

  resources :users
  resources :picks, except: :new
  match 'emails/create' => 'emails#create', :via => :post
  get  'login',  to: 'sessions#login'
  post 'login',  to: 'sessions#begin'
  get  'logout', to: 'sessions#end'

  get  'signup', to: 'users#new', as: 'signup'
  post 'signup', to: 'users#create'

  get  'landing',  to: 'application#landing'

end

app/models/pick.rb
class Pick < ActiveRecord::Base

	before_save { |pick| pick.assign_draw_id; pick.set_date_to_next_draw  }
  after_save { |pick| pick.setresult }

  validates :number, presence: true
  validates :game, presence: true
  validates :draw_date, presence: true
  validates_uniqueness_of :user, scope: [:number, :game, :draw_date]

  belongs_to :user
  belongs_to :draw

  def send_email
    if self.draw_date < Time.now
      Notifier.email_for_past_draw(self).deliver
    else
      Notifier.email_for_future_draw(self).deliver
    end
  end

	def set_date_to_next_draw
    if self.draw_date == nil && self.draw_id
      self.update(draw_date: draw.set_date(self))
    end
  end

  def assign_draw_id
    draws = Draw.where(game: self.game)
    draw = draws.find_by(draw_date: self.draw_date)
    if draw
      self.draw_id = draw.id
    end
  end

  def setresult
    if self.result == nil && self.draw_id != nil
      self.update(result: (draw.find_score(self)))
    end
  end
end

app/controllers/picks_controller.rb
class PicksController < ApplicationController
  before_action :require_login, except: [:create, :index, :destroy]
  before_action :join_number

  def index
    if params[:pick][:email]
        @user = User.find_by(email: params[:pick][:email])
    else
      @user = User.find(session[:user_id])
    end
    if @user
      @picks = User.find(@user.id).picks
      respond_to do |format|
          format.json { render json: ActiveSupport::JSON.encode(@picks), status:200 }
        end
    else
      respond_to do |format|
          format.json { render json: 'user not found', status:400 }
        end
    end
  end
  def create
    @pick = Pick.new(pick_params)
    if params[:pick][:email]
        @user = User.find_by(email: params[:pick][:email])
    else
      @user = User.find(session[:user_id])
    end
    if @pick.save
      user_picks_before_push = @user.picks.count
      @user.picks << @pick
      user_picks_after_push = @user.picks.count
      if user_picks_before_push == user_picks_after_push
        respond_to do |format|
          format.json { render json: 'fail to create pick', status:400 }
          format.html {
            flash[:error] = 'You have already created this Pick Number, please try again.'
              redirect_to user_path(@user)
            }
        end
      else
          respond_to do |format|
            format.json { render json: ActiveSupport::JSON.encode(@pick), status:200 }
            format.html {
              redirect_to user_path(@user)
            }
          end
      end
    else
       respond_to do |format|
          format.json { render json: 'fail to create pick', status:400 }
            format.html {
              flash[:error] = 'Failed to create entry... please try again.'
              redirect_to user_path(@user)
            }
       end
     end
   end

   def destroy
    @pick = Pick.find(params[:id])
    if @pick
      @pick.destroy
      respond_to do |format|
          format.json { render json: 'pick destroyed', status:200 }
          format.html {
            redirect_to user_path(@pick.user)
          }
      end
    else
      respond_to do |format|
          format.json { render json: 'pick not found', status:400 }
      end
    end
   end

   private
   def join_number
    nums_array = []
    if !params[:pick]
      return nil
    else
      (1..6).each do |num|
        number = "number" + num.to_s
        if params[:pick][number]
          nums_array << params[:pick][number]
        end
      end
    end
    if !params[:pick][:number]
      params[:pick][:number] = nums_array.join(" ")
    end
   end

    def pick_params
      params.require(:pick).permit(:number, :game, :draw_date, :multiplier)
    end
 end

app/views/picks/new.html.erb
<div id="msform">
  <ul id="progressbar">
    <li class="active">Your Picks</li>
    <li>Lottery Info</li>
    <li>LotifyMe</li>
  </ul>
  <div class="form-content">
    <%= form_tag(picks_path, method: "post") do %>
    <fieldset class = 'field-section'>
      <h2 class="fs-title">Lotto Info</h2>
      <h3 class="fs-subtitle">Please Provide Some Game Information</h3>
       <h3 class="fs-title"> Select the Game:</h3>
       <select name='pick[game]'>
          <option value="MegaMillion">Mega Millions</option>
          <option value="Powerball">Power Ball</option>
          <option value="NyLotto">NY Lotto</option>
          <option value="Cash4Life">Cash4Life</option>
          <!-- <option value="Take5">Take5</option>
          <option value="Pick10">Pick10</option> -->
        </select>
      <h4 class="fs-title"> Draw Date</h4>
      <%= date_field_tag 'pick[draw_date]', nil, placeholder: 'date' %>
      <a href="#" class="next action-button">Next</a>
    </fieldset>
    <fieldset class = 'field-section'>
    <div class="first-page">
    <h2 class="fs-title">What are your Lotto Numbers?</h2>
      <div class="row">
        <ul class="small-block-grid-6 small-centered columns large-block-grid-6 large-centered columns">
          <li><%= text_field_tag 'pick[number1]', nil, class: "small-centered-6 columns large-6 columns", maxlength: 2, step: 1, placeholder:'0' %></li>
          <li><%= text_field_tag 'pick[number2]',nil, class: "small-centered-6 columns large-6 columns", maxlength: 2, step: 1, placeholder:'0' %></li>
          <li><%= text_field_tag 'pick[number3]',nil, class: "small-centered-6 columns large-6 columns", maxlength: 2, step: 1, placeholder:'0'%></li>
          <li><%= text_field_tag 'pick[number4]',nil, class: "small-centered-6 columns large-6 columns", maxlength: 2, step: 1, placeholder:'0'%></li>
          <li><%= text_field_tag 'pick[number5]',nil, class: "small-centered-6 columns large-6 columns", maxlength: 2, step: 1, placeholder:'0'%></li>
          <li> <%= text_field_tag 'pick[number6]',nil, class: "small-centered-6 columns large-6 columns", maxlength: 2, step: 1,
          placeholder:'0'%></li>
          <h2 class="fs-title">If you have a multiplier, check box: </h2>
            <%= check_box_tag 'pick[multiplier]'%>
          </ul>
        </div>
      </div>
          <a href="#" class="next action-button">Next</a>
          <a href="#" class="previous">Previous</a>
    </fieldset>

    <fieldset class = 'field-section'>
        <% if !session[:user_id] %>
          <h2 class="fs-title">LotifyMe</h2>
          <h3 class="fs-subtitle">Enter Your Email:</h3>
          <%= email_field_tag 'pick[email]', nil, placeholder: 'email' %>
          <%= submit_tag 'Create and account', class: "important" %>
          <%= submit_tag 'Just send me an email', class: "no_important"%>
        <% else %>
          <%= hidden_field_tag 'pick[email]',"#{User.find(session[:user_id]).email}"%>
          <%= submit_tag 'Done', class: "action-button" %>
        <% end %>
        <a href="#" class="previous">Previous</a>
    </fieldset>

    <% end %>
  </div>
</div>

app/views/picks/show.html.erb
<div id="msform">
  <ul id="progressbar">
    <li class="active">Your Picks</li>
    <li>Lottery Info</li>
    <li>LotifyMe</li>
  </ul>
  <div class="form-content">
    <%= form_tag(picks_path, method: "post") do %>
    <fieldset class = 'field-section'>
      <h2 class="fs-title">Lotto Info</h2>
      <h3 class="fs-subtitle">Please Provide Some Game Information</h3>
       <h3 class="fs-title"> Select the Game:</h3>
       <select name='pick[game]'>
          <option value="MegaMillion">Mega Millions</option>
          <option value="Powerball">Power Ball</option>
          <option value="NyLotto">NY Lotto</option>
          <option value="Cash4Life">Cash4Life</option>
          <!-- <option value="Take5">Take5</option>
          <option value="Pick10">Pick10</option> -->
        </select>
      <h4 class="fs-title"> Draw Date</h4>
      <%= date_field_tag 'pick[draw_date]', nil, placeholder: 'date' %>
      <a href="#" class="next action-button">Next</a>
    </fieldset>
    <fieldset class = 'field-section'>
    <div class="first-page">
    <h2 class="fs-title">What are your Lotto Numbers?</h2>
      <div class="row">
        <ul class="small-block-grid-6 small-centered columns large-block-grid-6 large-centered columns">
          <li><%= text_field_tag 'pick[number1]', nil, class: "small-centered-6 columns large-6 columns", maxlength: 2, step: 1, placeholder:'0' %></li>
          <li><%= text_field_tag 'pick[number2]',nil, class: "small-centered-6 columns large-6 columns", maxlength: 2, step: 1, placeholder:'0' %></li>
          <li><%= text_field_tag 'pick[number3]',nil, class: "small-centered-6 columns large-6 columns", maxlength: 2, step: 1, placeholder:'0'%></li>
          <li><%= text_field_tag 'pick[number4]',nil, class: "small-centered-6 columns large-6 columns", maxlength: 2, step: 1, placeholder:'0'%></li>
          <li><%= text_field_tag 'pick[number5]',nil, class: "small-centered-6 columns large-6 columns", maxlength: 2, step: 1, placeholder:'0'%></li>
          <li> <%= text_field_tag 'pick[number6]',nil, class: "small-centered-6 columns large-6 columns", maxlength: 2, step: 1,
          placeholder:'0'%></li>
          <h2 class="fs-title">If you have a multiplier, check box: </h2>
            <%= check_box_tag 'pick[multiplier]'%>
          </ul>
        </div>
      </div>
          <a href="#" class="next action-button">Next</a>
          <a href="#" class="previous">Previous</a>
    </fieldset>

    <fieldset class = 'field-section'>
        <%= submit_tag 'Done', class: "action-button" %>
        <a href="#" class="previous">Previous</a>
    </fieldset>
    <% end %>
  </div>
</div>