config/routes.rb
Rails.application.routes.draw do

  root 'application#landing'

  resources :users
  resources :picks, except: :new
  match 'emails/create' => 'emails#create', :via => :post
  get  'login',  to: 'sessions#login'
  post 'login',  to: 'sessions#begin'
  get  'logout', to: 'sessions#end'

  get  'signup', to: 'users#new', as: 'signup'
  post 'signup', to: 'users#create'

  get  'landing',  to: 'application#landing'

end

app/views/layouts/_navigation.html.erb
    <nav class="tab-bar show-for-small">
      <a href='' class="left-off-canvas-toggle menu-icon" aria-expanded="false">
        <span></span>
      </a>
    </nav>
  <aside class="left-off-canvas-menu">
        <ul class="off-canvas-list">
          <% if !session[:user_id] %>
            <li><label class="first">Welcome</label></li>
            <li class = 'off-canvas-list-item'><%= link_to 'Home', root_path %></li>
            <li class = 'off-canvas-list-item'><%= link_to 'Login', login_path %></li>
            <li class = 'off-canvas-list-item'><%= link_to 'Sign up', signup_path %></li>
          <% else %>
            <% @session_id = session[:user_id] %>
            <li><label class="first"><%= User.find(@session_id).username %></label></li>
            <li class = 'off-canvas-list-item'><%= link_to 'My picks', user_path(@session_id) %></li>
            <li class = 'off-canvas-list-item'><%= link_to 'Edit profile', edit_user_path(@session_id) %></li>
            <li class = 'off-canvas-list-item'><%= link_to 'Logout', logout_path %></li>
          <% end %>
        </ul>
        <ul class="off-canvas-list">
          <li><label class="first">Learn</label></li>
          <li class = 'off-canvas-list-item'><a href="/">Features</a></li>
          <li class = 'off-canvas-list-item'><a href="/login">FAQ</a></li>
        </ul>
  </aside>
  <nav class="top-bar hide-for-small height" data-topbar>
      <ul class="title-area">
      </ul>
      <section class="top-bar-section">
        <ul class="right">
          <% if !session[:user_id] %>
              <li class = 'nav_list'><%= link_to 'Home', root_path %></li>
              <li class = 'nav_list'><%= link_to 'Login', login_path %></li>
              <li class = 'nav_list'><%= link_to 'Sign Up', signup_path %></li>
         <% else %>
         <% @session_id = session[:user_id] %>
            <% if User.find(@session_id).username %>
              <li class = 'nav_list'><a href="" id="username"><%= User.find(@session_id).username %></li></a>
            <% end %>
              <li class='navrigth nav_list'><%= link_to 'My Picks', user_path(@session_id) %></li>
              <li class='navrigth nav_list'><%= link_to 'Edit Profile', edit_user_path(@session_id) %></li>
              <li class='nav_list'><%= link_to 'Logout', logout_path %></li>
         <% end %>
       </ul>
    </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LotifyMe - Beta</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link rel="shortcut icon" href="<%= asset_path 'favicon-32x32.png' %>">
  <meta name="viewport" content="width=device-width, initial-scale=1.0,maximum-scale = 1.0" />
  <meta name="author" content="Daniel Rodriguez, Daniel K Chan, Stephanie Barreyro, Carl Schubert">
    <meta name="description" content="lottery notification app that makes searching and getting results much easier. If the draw was in the past, we tell you if you won, and if it's in the future we will tell you as soon as the draw happens if you won.  No more forgetting about lottery tickets, or spending time figuring out where to check for results and more time getting your lottery money and spending it.">
    <meta name="keywords" content="lottery, lotto, Powerball, Mega Millions, Ny Lotto, new york lotto, cahs 4 life, millionare, billionare, rich, jackpot, game, jackpot games, millions">
</head>
<body >
  <div class="off-canvas-wrap" data-offcanvas>
    <div class="inner-wrap">
      <header>
        <%= render partial: "/layouts/navigation", locals: {user: @user }%>
      </header>
      <% if flash[:error] %>
        <div class='error_message'><p class="notice"><%= flash[:error] %></p></div>
      <% elsif flash[:notice] %>
        <div class='notice_message'><p class="notice"><%= flash[:notice] %></p></div>
      <% end -%>
      <section class="main-section">
        <%= yield %>
      </section>
      <a class="exit-off-canvas" href="#"></a>
  </div>
</div>

</body>

</html>